# Basic Workflow
name: Deploy to AWS

on:
  # Triggers workflow on push or pull but only on the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that run in parallel
jobs:
  # This workflow contains singular job called build
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps contains a sequence of tasks that will be exacuted as part of the job
    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup NodeJS environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 16.17.1

      # Run a set of commands using the runner shell
      - name: Run a multiline script
        run: |
          npm install
          npm run build

      # Sync s3
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'
          SOURCE_DIR: 'dist'
    
      # Clears the cloudfront cache so new request will recieve the latest version of you app
      - name: Invalidate Cloudfront
      - uses: chetan/invalidate-cloudfront-action@v2.4
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: '/*'
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    
